/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppCounter: typeof import('./components/AppCounter.vue')['default']
    AppMarquee: typeof import('./components/AppMarquee.vue')['default']
    AppPageHeader: typeof import('./components/AppPageHeader.vue')['default']
    AppSwiper: typeof import('./components/AppSwiper.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAbout: typeof import('./components/TheAbout.vue')['default']
    TheBars: typeof import('./components/TheBars.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFaq: typeof import('./components/TheFaq.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheForm: typeof import('./components/TheForm.vue')['default']
    TheHero: typeof import('./components/TheHero.vue')['default']
    TheInfoSquares: typeof import('./components/TheInfoSquares.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheSquad: typeof import('./components/TheSquad.vue')['default']
    TheTopBar: typeof import('./components/TheTopBar.vue')['default']
  }
}
